apiVersion: v2
name: aws-nlb-nextcloud
version: 4.6.6
appVersion: 28.0.2
description: Fork from nextcloud community for aws-eks nlb controller
keywords:
  - nextcloud
  - storage
  - http
  - web
  - php
maintainers:
  - name: BrenKenna
    email: brendan.kenna.bk@gmail.com
dependencies:
  - name: postgresql
    version: 12.12.*
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: mariadb
    version: 12.2.*
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mariadb.enabled
  - name: redis
    version: 17.13.*
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
